import {
  create_proof as createProof,
  setup_generic_prover_and_verifier as setupGenericProverAndVerifier,
  StandardExampleProver,
  StandardExampleVerifier,
  verify_proof as verifyProof,
} from "@noir-lang/barretenberg/dest/client_proofs";
import { acir_from_bytes as acirFromBytes } from "@noir-lang/noir_wasm";
import { readFileSync } from "fs";

export type ACIR = any;
export type Proof = any;
export type Input = any;

/**
 * Represents a Noir Circuit backed by an ACIR
 */
export class Circuit {
  private prover?: StandardExampleProver;
  private verifier?: StandardExampleVerifier;

  /**
   * Creates a new instance given an ACIR
   * @param acir acir as returned by acir_from_bytes from noir_wasm
   */
  constructor(private acir: ACIR) {}

  /**
   * Returns the ACIR for this circuit
   * @returns precompiled ACIR as returned by acir_from_bytes in noir_wasm
   */
  public getACIR(): ACIR {
    return this.acir;
  }

  /**
   * Creates a proof for the given input
   * @param input object with expected input for the circuit (the order of keys matters!)
   * @returns a proof as generated by create_proof in barretenberg
   */
  public async getProof(input: Input): Promise<Proof> {
    const [prover, _verifier] = await this.getProverAndVerifier();
    return createProof(prover, this.acir, input);
  }

  /**
   * Verifies a proof
   * @param input a proof as generated by create_proof in barretenberg
   * @returns whether the proof is valid
   */
  public async verifyProof(proof: Proof): Promise<boolean> {
    const [_prover, verifier] = await this.getProverAndVerifier();
    return verifyProof(verifier, proof);
  }

  /**
   * Generates and verifies a proof for the given input
   * @param input object with expected input for the circuit (the order of keys matters!)
   * @returns whether the proof is valid
   */
  public async verifyProofFor(input: Input): Promise<boolean> {
    const proof = await this.getProof(input);
    return this.verifyProof(proof);
  }

  protected async getProverAndVerifier(): Promise<
    [StandardExampleProver, StandardExampleVerifier]
  > {
    if (!this.prover || !this.verifier) {
      [this.prover, this.verifier] = await setupGenericProverAndVerifier(
        this.acir
      );
    }
    return [this.prover, this.verifier];
  }
}

/**
 * Loads a circuit from an ACIR file
 * @param path path to the .acir file
 * @returns a Circuit object
 */
export function loadCircuit(path: string): Circuit {
  const buffer = new Uint8Array(readFileSync(path));
  const acir: ACIR = acirFromBytes(buffer);
  return new Circuit(acir);
}
